POST http://localhost:3333/create
Content-Type: application/json
Accept-Language: "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7"

{
  "title": "COnTeudo",
  "content": "conteudo",
  "author": "Daniel"
}


###

POST http://localhost:3333/create
Content-Type: application/json
Accept-Language: "pt-BR,pt;q=0.9,en-US;q=0.8,en;q=0.7"

{
  "title": "Gostei",
  "first_paragraph": "Gostei de você",
  "second_paragraph": "A conexão com o banco de dados é feita de forma simples e segura.",
  "third_paragraph": "Ao final, você será capaz de realizar inserções, leituras e outras operações com facilidade.",
  "image": "https://via.placeholder.com/600x400",
  "type": "tutorial",
  "genre": "tecnologia",
  "user_id": "user-123"
}



###

GET http://localhost:3333/public/posts

###

PUT http://localhost:3333/edit/575ec9de-fe09-4762-a99f-bc5c5333a918
Content-Type: application/json  


{
  "title": "tudo errado",
  "first_paragraph": "Gosteisadadasdasddaadsadasd",
  "second_paragraph": "A conexão com o banco de dados é feita de forma simples e segura.",
  "third_paragraph": "Ao final, você será capaz de realizar inserções, leituras e outras operações com facilidade.",
  "image": "https://via.placeholder.com/600x400",
  "type": "tutorial",
  "genre": "tecnologia",
  "user_id": "user-123"
}

###

DELETE  http://localhost:3333/delete/575ec9de-fe09-4762-a99f-bc5c5333a918

